name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        working-directory: shipping
        run: mvn clean install

      - name: Run tests
        working-directory: shipping
        run: mvn test

      - name: Package the application
        working-directory: shipping
        run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Deploy application
        env:
          DEPLOY_SERVER: 13.60.167.146
          DEPLOY_USER: ubuntu
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          scp -i $DEPLOY_KEY shipping/target/shipping-0.0.1-SNAPSHOT.jar $DEPLOY_USER@$DEPLOY_SERVER:/
          ssh -i $DEPLOY_KEY $DEPLOY_USER@$DEPLOY_SERVER "bash /deploy.sh"
